---
title: "Supply-Calcium"
author: "Gareth Osman"
date: '2022-11-21'
output: html_document
---

> Packages

```{r}
library(tidyverse)
```

>Data

```{r}
ihs5 <- read.csv(here::here('hh_mod_g_final.csv'))
ihs5 <- select(ihs5, -X)

hh.hme <- read.csv(here::here('hme.final.csv'))
hh.hme <- select(hh.hme, -X)

```


>Food group analysis dummy data frames

```{r}
#Disaggregation by food groups
cereal <- ihs5 %>% filter(food.group=="Cereals")
veg <- ihs5 %>% filter(food.group=="Vegetables")
meat <- ihs5 %>% filter(food.group=="Meat")
fat <- ihs5 %>% filter(food.group=="Fats & oils")
leg <- ihs5 %>% filter(food.group=="Legumes & nuts")
fruit <- ihs5 %>% filter(food.group=="Fruits")
fish <- ihs5 %>% filter(food.group=="Fish")
sugary <- ihs5 %>% filter(food.group=="Sugary foods/beverages")
dairy <- ihs5 %>% filter(food.group=="Milk & milk products")
egg <- ihs5 %>% filter(food.group=="Eggs")
tuber <- ihs5 %>% filter(food.group=="Roots & tubers")
misc <- ihs5 %>% filter(food.group=="Miscellaneous")

```

>Calcium Supply

```{r}
#MN supply/food item = multiply quantity of foods consumed with MN composition of food
ihs5$ca.supply <- ihs5$g100_d_nep2*ihs5$CA
#HH MN supply = Aggregate MN supply from all food items 
d.ca <- aggregate(ihs5$ca.supply, by=list(HHID=ihs5$HHID), FUN=sum)
#Merged DF with all dietary variables
ihs5.ca <- merge(x=hh.hme, y=d.ca , by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)

ihs5.ca <- ihs5.ca %>% rename(ca.supply = 'sum.ihs5$ca.supply')

ihs5.ca <- ihs5.ca %>% filter(!is.na(ca.supply))

#Food group analysis
cereal$ca.supply <- cereal$g100_d_nep2*cereal$CA
tuber$ca.supply <- tuber$g100_d_nep2*tuber$CA
leg$ca.supply <- leg$g100_d_nep2*leg$CA
veg$ca.supply <- veg$g100_d_nep2*veg$CA
meat$ca.supply <- meat$g100_d_nep2*meat$CA
fruit$ca.supply <- fruit$g100_d_nep2*fruit$CA
dairy$ca.supply <- dairy$g100_d_nep2*dairy$CA
fat$ca.supply <- fat$g100_d_nep2*fat$CA
misc$ca.supply <- misc$g100_d_nep2*misc$CA
egg$ca.supply <- egg$g100_d_nep2*egg$CA
sugary$ca.supply <- sugary$g100_d_nep2*sugary$CA
fish$ca.supply <- fish$g100_d_nep2*fish$CA

#Aggregate ca supply per food group
cereal.ca <- aggregate(cereal$ca.supply, by=list(HHID=cereal$HHID), FUN=sum)
tuber.ca <- aggregate(tuber$ca.supply, by=list(HHID=tuber$HHID), FUN=sum)
leg.ca <- aggregate(leg$ca.supply, by=list(HHID=leg$HHID), FUN=sum)
veg.ca <- aggregate(veg$ca.supply, by=list(HHID=veg$HHID), FUN=sum)
meat.ca <- aggregate(meat$ca.supply, by=list(HHID=meat$HHID), FUN=sum)
fruit.ca <- aggregate(fruit$ca.supply, by=list(HHID=fruit$HHID), FUN=sum)
dairy.ca <- aggregate(dairy$ca.supply, by=list(HHID=dairy$HHID), FUN=sum)
fat.ca <- aggregate(fat$ca.supply, by=list(HHID=fat$HHID), FUN=sum)
misc.ca <- aggregate(misc$ca.supply, by=list(HHID=misc$HHID), FUN=sum)
egg.ca <- aggregate(egg$ca.supply, by=list(HHID=egg$HHID), FUN=sum)
sugary.ca <- aggregate(sugary$ca.supply, by=list(HHID=sugary$HHID), FUN=sum)
fish.ca <- aggregate(fish$ca.supply, by=list(HHID=fish$HHID), FUN=sum)

#Merged DF with all dietary variables
ihs5.ca <- merge(x=ihs5.ca, y=cereal.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=tuber.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=leg.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=veg.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=meat.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=fruit.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=dairy.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=fat.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=misc.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=egg.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=sugary.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- merge(x=ihs5.ca, y=fish.ca, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)

#Rename aggregated food group variables
ihs5.ca <- ihs5.ca %>% rename(ca.cereal = 'sum.cereal$ca.supply',
                                      ca.tuber = 'sum.tuber$ca.supply',
                                      ca.leg = 'sum.leg$ca.supply',
                                      ca.veg = 'sum.veg$ca.supply',
                                      ca.meat = 'sum.meat$ca.supply',
                                      ca.fruit = 'sum.fruit$ca.supply',
                                      ca.dairy = 'sum.dairy$ca.supply',
                                      ca.fat = 'sum.fat$ca.supply',
                                      ca.misc = 'sum.misc$ca.supply',
                                      ca.egg = 'sum.egg$ca.supply',
                                      ca.sugary = 'sum.sugary$ca.supply',
                                      ca.fish = 'sum.fish$ca.supply')

```

>Two METRICS TO MEASURE BROKEN UP INTO TWO CATEGORIES:

**CATEGORY 1: APPARENT INTAKE**



#1. Supply per AFE

```{r}
#MN supply/AFE
ihs5.ca$ai.afe <- ihs5.ca$ca.supply/ihs5.ca$afe
#AFE inadequacy
ihs5.ca <- ihs5.ca %>% mutate(afe.inad = ifelse(ai.afe<860, "Inadequate", "Adequate"))
```

**CATEGORY 2: NUTRIENT DENSITY**

#2. Nutrient Density of HH

```{r}
#MN density
ihs5.energy <- read.csv(here::here('ihs5.energy.csv'))
  
ihs5.eden <- ihs5.energy %>% select(HHID, energy.supply)
ihs5.ca <- merge(x=ihs5.ca, y=ihs5.eden, by.x='HHID', by.y='HHID', fill=-9999, all.x = TRUE)
ihs5.ca <- ihs5.ca %>% mutate(den = ca.supply/energy.supply*1000)

#MN Density inadequacy
ihs5.ca <- ihs5.ca %>% mutate(den.inad = ifelse(den<(860/2.100), "Inadequate", "Adequate"))
```

> DONE: archive